<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Majorsoft.Blazor.Components.Collapse" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Common.JsInterop" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.CssEvents" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Debounce" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.GdprConsent" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Inputs" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Loading" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Maps" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Modal" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Notifications" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.PermaLink" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Tabs" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Timer" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Toggle" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Typeahead" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.WASM.AppLoader" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Extensions.Analytics" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Extensions.BrowserStorage" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.Server.Logging.Console" Version="2.1.0" />
    <PackageReference Include="Majorsoft.Blazor.WebAssembly.Logging.Console" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.9" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>
</Project>
