<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<nullable>enable</nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Majorsoft.Blazor.Components.Tabs</PackageId>
		<Version>1.0.0.0</Version>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>full</TrimMode>
		<InvariantGlobalization>false</InvariantGlobalization>
		<Authors>Imre Toth</Authors>
		<Company>Majorsoft</Company>
		<Product>Blazor Components</Product>
		<Copyright>©2021 Imre Toth</Copyright>
		<PackageLicenseExpression></PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/majorimi/blazor-components/blob/master/.github/docs/Tabs.md</PackageProjectUrl>
    <PackageReadmeFile>Tabs.md</PackageReadmeFile>
    <PackageIcon>blazor.components.png</PackageIcon>
		<RepositoryUrl>https://github.com/majorimi/blazor-components</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageTags>.Net5 Blazor Tabs TabItem</PackageTags>
		<Description>Blazor component that renders customizable Tabs element panel with many tabs and custom content. Part of Majorsoft Blazor library.</Description>
		<PackageLicenseFile>License.txt</PackageLicenseFile>
		<PackageReleaseNotes>See Releases here: https://github.com/majorimi/blazor-components/releases</PackageReleaseNotes>
		<Title>Blazor Components Tabs</Title>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="bundleconfig.json" />
	</ItemGroup>

	
	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.25" />
	</ItemGroup>

  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
  
	<ItemGroup>
		<None Include="..\..\.github\docs\Tabs.md" Link="Tabs.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
		<None Include="..\..\.github\Images\blazor.components.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\..\.github\License.txt">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="bundleconfig.json" />
	</ItemGroup>
	
	<!--Include project DLL output to Nuget package-->
	<ItemGroup>
		<ProjectReference PrivateAssets="all" Include="..\Majorsoft.Blazor.Components.Core\Majorsoft.Blazor.Components.Core.csproj" />
		<ProjectReference Include="..\Majorsoft.Blazor.Components.PermaLink\Majorsoft.Blazor.Components.PermaLink.csproj" />
	</ItemGroup>
	<ItemGroup>
		<_PackageFiles Include="$(OutputPath)\Majorsoft.Blazor.Components.Core.dll">
			<BuildAction>None</BuildAction>
			<PackagePath>lib\net5.0</PackagePath>
		</_PackageFiles>
	</ItemGroup>

</Project>
