<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<nullable>enable</nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Version>1.0.0.0</Version>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>full</TrimMode>
		<InvariantGlobalization>false</InvariantGlobalization>
		<PackageProjectUrl>https://github.com/majorimi/blazor-components/blob/master/.github/docs/Maps.md</PackageProjectUrl>
    <PackageReadmeFile>Maps.md</PackageReadmeFile>
		<Authors>Imre Toth</Authors>
		<Company>Majorsoft</Company>
		<Product>Blazor Components</Product>
		<RepositoryUrl>https://github.com/majorimi/blazor-components</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageTags>.Net5 Blazor GoogleMaps Leaflet Maps</PackageTags>
		<PackageIcon>blazor.components.png</PackageIcon>
		<PackageId>Majorsoft.Blazor.Components.Maps</PackageId>
		<PackageLicenseExpression></PackageLicenseExpression>
		<PackageReleaseNotes>See Releases here: https://github.com/majorimi/blazor-components/releases </PackageReleaseNotes>
		<Copyright>©2021 Imre Toth</Copyright>
		<Description>Blazor component for Google Maps and Leaflet maps integration. Part of Majorsoft Blazor library.</Description>
		<Title>Blazor Components Maps</Title>  
		<PackageLicenseFile>License.txt</PackageLicenseFile>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="bundleconfig.json" />
	</ItemGroup>

	
	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.25" />
	</ItemGroup>
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
  
	<ItemGroup>
	  <None Include="..\..\.github\docs\Maps.md" Link="Maps.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
	  <None Include="..\..\.github\Images\blazor.components.png">
	    <Pack>True</Pack>
	    <PackagePath></PackagePath>
	  </None>
	  <None Include="..\..\.github\License.txt">
	    <Pack>True</Pack>
	    <PackagePath></PackagePath>
	  </None>
	  <None Include="bundleconfig.json" />
	</ItemGroup>

	<!--Include project DLL output to Nuget package-->
	<ItemGroup>
		<ProjectReference Include="..\Majorsoft.Blazor.Components.Common.JsInterop\Majorsoft.Blazor.Components.Common.JsInterop.csproj" />
		<ProjectReference PrivateAssets="all" Include="..\Majorsoft.Blazor.Components.Core\Majorsoft.Blazor.Components.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<_PackageFiles Include="$(OutputPath)\Majorsoft.Blazor.Components.Core.dll">
			<BuildAction>None</BuildAction>
			<PackagePath>lib\net5.0</PackagePath>
		</_PackageFiles>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Bing\" />
	</ItemGroup>

</Project>