<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<nullable>enable</nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Majorsoft.Blazor.Components.PermaLink</PackageId>
		<Version>1.0.0.0</Version>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>full</TrimMode>
		<InvariantGlobalization>false</InvariantGlobalization>
		<Authors>Imre Toth</Authors>
		<Company>Majorsoft</Company>
		<Product>Blazor Components</Product>
		<Copyright>©2021 Imre Toth</Copyright>
		<PackageProjectUrl>https://github.com/majorimi/blazor-components/blob/master/.github/docs/PermaLink.md</PackageProjectUrl>
    <PackageReadmeFile>PermaLink.md</PackageReadmeFile>
		<PackageIcon>blazor.components.png</PackageIcon>
		<RepositoryUrl>https://github.com/majorimi/blazor-components</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageTags>.Net5 Blazor URL URI Routing Navigation PermaLink Link</PackageTags>
		<PackageReleaseNotes>See Releases here: https://github.com/majorimi/blazor-components/releases</PackageReleaseNotes>
		<Description>Blazor PermaLink component and extension that can be used to create navigation element inside Blazor pages (#permalink). Part of Majorsoft Blazor library.</Description>
		<Title>Blazor Components PermaLink navigation</Title>
		<PackageLicenseFile>License.txt</PackageLicenseFile>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>
	
	<ItemGroup>
		<Content Remove="bundleconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.25" />
	</ItemGroup>

  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
  
	<ItemGroup>
		<ProjectReference Include="..\Majorsoft.Blazor.Components.Common.JsInterop\Majorsoft.Blazor.Components.Common.JsInterop.csproj" />
	</ItemGroup>
	<!--Include project DLL output to Nuget package-->
	<ItemGroup>
		<ProjectReference PrivateAssets="all" Include="..\Majorsoft.Blazor.Components.Core\Majorsoft.Blazor.Components.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<_PackageFiles Include="$(OutputPath)\Majorsoft.Blazor.Components.Core.dll">
			<BuildAction>None</BuildAction>
			<PackagePath>lib\net5.0</PackagePath>
		</_PackageFiles>
	</ItemGroup>

	<ItemGroup>
	<None Include="..\..\.github\docs\PermaLink.md" Link="PermaLink.md">
    <Pack>True</Pack>
    <PackagePath></PackagePath>
  </None>
	<None Include="..\..\.github\Images\blazor.components.png">
		<Pack>True</Pack>
		<PackagePath></PackagePath>
	</None>
	<None Include="..\..\.github\License.txt">
		<Pack>True</Pack>
		<PackagePath></PackagePath>
	</None>
	<None Include="bundleconfig.json" />
	</ItemGroup>

</Project>
