<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Majorsoft.Blazor.Components.Collapse" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Common.JsInterop" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.CssEvents" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Debounce" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.GdprConsent" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Inputs" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Loading" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Maps" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Modal" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Notifications" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.PermaLink" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Tabs" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Timer" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Toggle" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.Typeahead" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Components.WASM.AppLoader" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Extensions.Analytics" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.Extensions.BrowserStorage" Version="2.0.0" />
    <PackageReference Include="Majorsoft.Blazor.WebAssembly.Logging.Console" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
  </ItemGroup>

</Project>
