<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<nullable>enable</nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Majorsoft.Blazor.Components.Timer</PackageId>
		<Version>1.0.0.0</Version>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>full</TrimMode>
		<InvariantGlobalization>false</InvariantGlobalization>
		<Authors>Imre Toth</Authors>
		<Company>Majorsoft</Company>
		<Product>Blazor Components</Product>
		<Copyright>©2021 Imre Toth</Copyright>
		<PackageLicenseExpression></PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/majorimi/blazor-components/blob/master/.github/docs/Timer.md</PackageProjectUrl>
    <PackageReadmeFile>Timer.md</PackageReadmeFile>
    <PackageIcon>blazor.components.png</PackageIcon>
		<RepositoryUrl>https://github.com/majorimi/blazor-components</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageTags>.Net5 Blazor Timer</PackageTags>
		<Description>Blazor component that can be used for scheduled and periodically repeated tasks to call custom code. Part of Majorsoft Blazor library.</Description>
		<PackageLicenseFile>License.txt</PackageLicenseFile>
		<PackageReleaseNotes>See Releases here: https://github.com/majorimi/blazor-components/releases</PackageReleaseNotes>
		<Title>Blazor Components Timer</Title>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.25" />
	</ItemGroup>

  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
  
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Majorsoft.Blazor.Components.Debounce</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	
	<ItemGroup>
	<None Include="..\..\.github\docs\Timer.md" Link="Timer.md">
    <Pack>True</Pack>
    <PackagePath></PackagePath>
  </None>
	<None Include="..\..\.github\Images\blazor.components.png">
		<Pack>True</Pack>
		<PackagePath></PackagePath>
	</None>
	<None Include="..\..\.github\License.txt">
		<Pack>True</Pack>
		<PackagePath></PackagePath>
	</None>
	</ItemGroup>

</Project>
