<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<nullable>enable</nullable>
		<Version>1.0.0.0</Version>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>full</TrimMode>
		<InvariantGlobalization>false</InvariantGlobalization>
		<PackageIcon>blazor.components.png</PackageIcon>
		<PackageId>Majorsoft.Blazor.Components.Collapse</PackageId>
		<Authors>Imre Toth</Authors>
		<Company>Majorsoft</Company>
		<Product>Blazor Components</Product>
		<Copyright>©2021 Imre Toth</Copyright>
		<PackageLicenseExpression></PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/majorimi/blazor-components/blob/master/.github/docs/Collapse.md</PackageProjectUrl>
    <PackageReadmeFile>Collapse.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/majorimi/blazor-components</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageTags>.Net5 Blazor Collapse Expand Accordion</PackageTags>
		<PackageReleaseNotes>See Releases here: https://github.com/majorimi/blazor-components/releases</PackageReleaseNotes>
		<Description>Blazor component that renders a customizable Expand/Collapse element also supports Collapse group (accordion). Part of Majorsoft Blazor library.</Description>
		<Title>Blazor Components Expand/Collapse</Title>
		<PackageLicenseFile>License.txt</PackageLicenseFile>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="bundleconfig.json" />
	</ItemGroup>

	<ItemGroup>
    <None Include="..\..\.github\docs\Collapse.md" Link="Collapse.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
		<None Include="..\..\.github\Images\blazor.components.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\..\.github\License.txt">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="bundleconfig.json" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.25" />
	</ItemGroup>
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

	<!--Include project DLL output to Nuget package-->
	<ItemGroup>
		<ProjectReference PrivateAssets="all" Include="..\Majorsoft.Blazor.Components.Core\Majorsoft.Blazor.Components.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<_PackageFiles Include="$(OutputPath)\Majorsoft.Blazor.Components.Core.dll">
			<BuildAction>None</BuildAction>
			<PackagePath>lib\net5.0</PackagePath>
		</_PackageFiles>
	</ItemGroup>

</Project>